---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  todos.sql: "CREATE TABLE todos ( item text, mimetype text, image text );"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  # client
  #   https://www.postgresql.org/docs/current/libpq-envars.html
  PGHOST: "postgres"
  PGPORT: "5432"
  PGSSLMODE: "disable"
  # both
  #   https://www.postgresql.org/docs/current/libpq-envars.html
  #   https://hub.docker.com/r/library/postgres
  PGUSER: "pguser"
  POSTGRES_USER: "pguser"
  
  PGDATABASE: "pgdb"
  POSTGRES_DB: "pgdb"

  PGPASSWORD: "pgpass"
  POSTGRES_PASSWORD: "pgpass"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: postgres
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
          - name: postgres-init
            mountPath: /docker-entrypoint-initdb.d/
          - name: host-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
        - name: host-storage
          hostPath:
            path: /data/postgres
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
  selector:
    app: postgres
